---
root: true

env:
  browser: true
  es2021: true
  jest: true
  node: true

plugins:
  - jest
  - babel

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"

parser: "@babel/eslint-parser"

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
